events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/json;

    # Upstream services
    upstream auth_service {
        server auth-service:3001;
    }

    upstream score_service {
        server score-service:3002;
    }

    server {
        listen 80;
        server_name localhost;

        # Root Endpoint / Gateway Info
        location = / {
            return 200 '{"status":"online","gateway":"Academic Microservice API Gateway","version":"1.0.0","endpoints":{"auth":"/api/auth/","score":"/api/score/"}}';
            add_header Content-Type application/json;
        }

        # Sub-layanan Auth (Authentication & Accounts)
        location /api/auth/ {
            proxy_pass http://auth_service/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_cache_bypass $http_upgrade;
        }

        # Sub-layanan Score (Penilaian & Perhitungan IPS)
        location /api/score/ {
            proxy_pass http://score_service/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_cache_bypass $http_upgrade;
        }
    }
}
